package com.qkart.enums;

public enum LogStatus {

    EXTENTINFO,
    EXTENTPASS,
    EXTENTFAIL,
    EXTENTSKIP,
    EXTENTSCREENSHOT,
    EXTENTTHOWABLE,
    LOG4JINFO,
    LOG4JERROR,
    LOG4JSTARTTEST,
    LOG4JENDTEST,
    LOG4JTESTINFO,
    LOG4JTESTERROR,
    EXRENTPASSLOG4JINFO,
    EXRENTFAILLOG4JERROR
}
